name: Staging Release and Publish

on:
  # TODO: Enabling manual workflow triggering while in pre-release mode. Remove when 1.8 is released
  workflow_dispatch:
    branches:
      - develop
    paths-ignore:
      - "docs/**"
      - "www/**"
      - ".github/**"
      

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Staging Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Configure npm node prepend 
        run: npm config set scripts-prepend-node-path auto

      - name: Install Dependencies
        run: yarn

<<<<<<< HEAD
      - name: Build all packages
        run: yarn build

      - name: Version packages
        run: yarn version:next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: yarn install --no-immutable
        
<<<<<<< HEAD
<<<<<<< HEAD
      - name: Publish staging packages
        run: yarn release:staging
=======
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with: 
          version: yarn version:staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> c54694323 (chore: rebase)
=======
      - name: Publish packages under next tag
        run: yarn release:next
>>>>>>> 726858d847c0152abc1c77799091f15c9910ea00
=======
      - name: Publish packages under next tag
        run: yarn release:next
>>>>>>> 27a29ef24e5ea1ba2bc0be8ecb7dd747d4c7c65b
